# Generated by Django 4.2.11 on 2024-06-20 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlines', models.IntegerField(blank=True, verbose_name='Срок выполнения')),
                ('object_name', models.CharField(blank=True, max_length=100, verbose_name='Название объекта')),
                ('total_area', models.IntegerField(blank=True, verbose_name='Общая прощадь')),
                ('living_area', models.IntegerField(blank=True, verbose_name='Жилая прощадь')),
                ('address', models.CharField(default='', max_length=150, verbose_name='Адрес')),
                ('wall_material', models.CharField(blank=True, max_length=100, verbose_name='Материал стен')),
                ('equipment', models.CharField(blank=True, max_length=100, verbose_name='Комплектация')),
                ('reviewer_name', models.CharField(default='', max_length=100, verbose_name='Имя клиента')),
                ('review', models.CharField(default='', max_length=1000, verbose_name='Отзыв клиента')),
            ],
            options={
                'verbose_name': 'Готовый проект',
                'verbose_name_plural': 'Готовые проекты',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название объекта')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание объекта')),
                ('total_area', models.IntegerField(blank=True, verbose_name='Общая прощадь')),
                ('living_area', models.IntegerField(blank=True, verbose_name='Жилая прощадь')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена базовой комплектации')),
                ('bedrooms', models.IntegerField(blank=True, verbose_name='Количество спален')),
                ('bathroom', models.IntegerField(blank=True, verbose_name='Количество санузлов')),
                ('floors', models.IntegerField(blank=True, verbose_name='Количество этажей')),
                ('terrace', models.BooleanField(blank=True, verbose_name='Наличие террасы')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('review', models.CharField(blank=True, max_length=2000, verbose_name='Отзыв')),
                ('review_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProjectLayouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.ImageField(upload_to=main.models.img_save)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.img_save)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.finished_project_img_save)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.finishedprojects')),
            ],
        ),
    ]
