# Generated by Django 4.2.11 on 2024-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_projects_price_projectprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная стоимость'),
        ),
    ]
