# Generated by Django 4.2.11 on 2024-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedprojects',
            name='living_area',
            field=models.IntegerField(blank=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='finishedprojects',
            name='total_area',
            field=models.IntegerField(blank=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='living_area',
            field=models.IntegerField(blank=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_area',
            field=models.IntegerField(blank=True, verbose_name='Общая площадь'),
        ),
    ]
