# Generated by Django 4.2.11 on 2024-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_finishedprojects_living_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Критерий')),
                ('price', models.IntegerField(blank=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Сделать дешевле',
                'verbose_name_plural': 'Сделать дешевле',
            },
        ),
    ]
