# Generated by Django 5.1.3 on 2024-11-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_makesale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Критерий (не менять)')),
                ('value', models.CharField(blank=True, max_length=150, verbose_name='Значение (можно менять)')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]
