# Generated by Django 4.1.10 on 2025-01-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_conactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=260, verbose_name='Название акции')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='Описание акции')),
                ('status', models.BooleanField(verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Добавить акцию',
                'verbose_name_plural': 'Добавить акцию',
            },
        ),
    ]
