# Generated by Django 6.0.3 on 2026-03-13 05:25

import datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offersale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(blank=True, max_length=100, verbose_name='Название статьи')),
                ('slug', models.SlugField(blank=True, help_text='Только буквы, цифры, дефисы и подчёркивания', unique=True, verbose_name='Слаг (для URL)')),
                ('article_text', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to=main.models.article_img_save)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('article_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
